export enum TreeActionType {
  ADD_CONDITION = "ADD_CONDITION",
  ADD_LOGIC = "ADD_LOGIC",
  REMOVE = "REMOVE",
  MODIFY_PROP = "MODIFY_PROP",
  MODIFY_OPERATOR = "MODIFY_OPERATOR",
  MODIFY_VALUE = "MODIFY_VALUE",
  MODIFY_LOGIC = "MODIFY_LOGIC",
  CLEAR_TREE = "CLEAR_TREE",
}
